### ISSUE TITLE
ScrambleDB Error Handling

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/atlas#2] opened 2023-08-03 13:55 UTC
Let's add this in a followup (for all the TODOs).
You can introduce a `CurveError` `Error` variant and implement a `From<p256::Error>` for it. Then we can replace all the `unwrap`s with `?`.

_Originally posted by @franziskuskiefer in https://github.com/cryspen/atlas/pull/1#discussion_r1282230076_

**Comment by jschneider-bensch** [comment] 2023-10-16 13:24
Duplicate of #15 .

**Closed by jschneider-bensch** 2023-10-16 13:24 UTC
